In [46]:
import numpy as np
import tensorflow as tf

# Input data (1000 samples and 100 dimensions, sampled from normal distribution mean 0 and variance 1
x = tf.Variable(tf.random_normal([1000, 100]))

# Weights (100 x 100) - fist hidden layer 100 neurons (again sampled from normal distribution)
w = tf.Variable(tf.random_normal([100, 100]))

# Let's pay attention to pre-activation (linear transformation) and post activation (sigmoid)
z = tf.matmul(x, w)
a = tf.sigmoid(z)

# Initialize variables
s = tf.Session()
s.run(x.initializer)
s.run(w.initializer)

print(s.run(x))
print(s.run(w))

[[-1.3506006  -1.44919395 -1.84073877 ...,  0.27401546  0.44146439
  -0.86240041]
 [ 0.18616559  1.9196769  -1.49231827 ...,  1.74128735  1.3574034
  -0.60781384]
 [ 0.4765659  -0.38291004  1.54308915 ..., -0.37201849  1.45425463
  -0.97414458]
 ..., 
 [-0.64884758  1.55176115 -0.77908283 ...,  0.47215492  0.35867131
   0.30688319]
 [-0.10884814  1.32305515  2.88238907 ...,  2.86241245  0.47126377
  -1.19728875]
 [-1.62330163  0.71584153  0.75232375 ...,  0.24022448 -0.75001138
  -0.88364369]]
[[ 0.95036864 -0.43992004 -1.27088678 ..., -0.00482269  0.80386508
   1.14012134]
 [-0.53637046 -1.30264688  1.73127592 ...,  1.32555246  0.12046738
   1.56219339]
 [-0.98681074  1.47597194 -1.32031608 ...,  0.56552452  0.7807622
   0.12444765]
 ..., 
 [ 1.70699966 -0.42112988  0.47572461 ...,  0.11053076 -2.66118693
   0.72965157]
 [-0.71429056 -2.34721828  1.54519451 ...,  0.10051571  0.00465609
   1.02849889]
 [-1.06370831  0.72901899  0.98082948 ..., -0.1381342  -2.01436043
   0.22796406]]


In [16]:
# Now pay attention to distribution of activation and post-activation values
np.histogram(s.run(z), 10)

(array([   31,   409,  3414, 14078, 29966, 31423, 16011,  4125,   503,    40]),
 array([-43.91438675, -35.2313446 , -26.54830246, -17.86526031,
         -9.18221817,  -0.49917603,   8.18386612,  16.86690826,
         25.54995041,  34.23299255,  42.9160347 ]))

In [17]:
np.histogram(s.run(a), 10) 

(array([41137,  3229,  2135,  1800,  1700,  1666,  1734,  2142,  3236, 41221]),
 array([  8.47664836e-20,   1.00000000e-01,   2.00000000e-01,
          3.00000000e-01,   4.00000000e-01,   5.00000000e-01,
          6.00000000e-01,   7.00000000e-01,   8.00000000e-01,
          9.00000000e-01,   1.00000000e+00]))

In [18]:
np.var(s.run(z))

101.00862

In [19]:
np.var(s.run(a))

0.21020295

# Questions:

1. What did you notice in the output ?
2. Then change activation function from sigmoid to relu and repeat this exercise

In [118]:
x = tf.Variable(tf.random_normal([1000, 100]))
w = tf.Variable(tf.random_normal([100, 100]))

z = tf.matmul(x, w)
a = tf.nn.relu(z)

s1 = tf.Session()
s1.run(x.initializer)
s1.run(w.initializer)

#print(s1.run(x))
#print(s1.run(w))

In [119]:
np.histogram(s1.run(z), 10)

(array([    5,   137,  1578,  9694, 27502, 34868, 20231,  5221,   710,    54]),
 array([-48.20395279, -39.12018852, -30.03642426, -20.95265999,
        -11.86889572,  -2.78513145,   6.29863281,  15.38239708,
         24.46616135,  33.54992561,  42.63368988]))

In [120]:
np.histogram(s1.run(a), 10) 

(array([66681, 13930,  9629,  5481,  2602,  1107,   413,   112,    39,     6]),
 array([  0.        ,   4.26336899,   8.52673798,  12.79010696,
         17.05347595,  21.31684494,  25.58021393,  29.84358292,
         34.1069519 ,  38.37032089,  42.63368988]))

In [121]:
np.var(s1.run(z))

98.421532

In [122]:
np.var(s1.run(a))

33.792439

3. Then change weight initialization to w = tf.Variable(tf.random_normal([1000, 100])*(1/tf.sqrt(100.0))) and repeat it.
4. What are you thinking now ...

In [106]:
x = tf.Variable(tf.random_normal([1000, 100]))
w = tf.Variable(tf.random_normal([100, 100])*(1/tf.sqrt(100.0)))

z = tf.matmul(x, w)
a = tf.nn.relu(z)

s2 = tf.Session()
s2.run(x.initializer)
s2.run(w.initializer)
#print(s2.run(x))
#print(s2.run(w))

In [107]:
np.histogram(s2.run(z), 10)

(array([    3,   111,  2147, 14722, 36699, 33878, 10985,  1385,    69,     1]),
 array([-5.25473309, -4.18380938, -3.11288567, -2.04196196, -0.97103825,
         0.09988546,  1.17080917,  2.24173288,  3.31265659,  4.3835803 ,
         5.45450401]))

In [108]:
np.histogram(s2.run(a), 10) 

(array([70457, 15452,  8729,  3663,  1249,   370,    61,    18,     0,     1]),
 array([ 0.        ,  0.5454504 ,  1.0909008 ,  1.6363512 ,  2.18180161,
         2.72725201,  3.27270241,  3.81815281,  4.36360321,  4.90905361,
         5.45450401]))

In [109]:
np.var(s2.run(z))

1.0417368

In [110]:
np.var(s2.run(a))

0.35686392

In [139]:
x = tf.Variable(tf.truncated_normal([1000, 100], stddev = 1.0))
w = tf.Variable(tf.truncated_normal([100, 100], stddev = 1.0))

z = tf.matmul(x, w)
a = tf.nn.relu(z)

s3 = tf.Session()
s3.run(x.initializer)
s3.run(w.initializer)
#print(s2.run(x))
#print(s2.run(w))

In [140]:
np.histogram(s3.run(z), 10)

(array([   82,   856,  5312, 18263, 32020, 27684, 12575,  2833,   348,    27]),
 array([-31.6075573 , -25.03357944, -18.45960159, -11.88562374,
         -5.31164589,   1.26233196,   7.83630981,  14.41028767,
         20.98426552,  27.55824337,  34.13222122]))

In [141]:
np.histogram(s3.run(a), 10) 

(array([67014, 13925,  9715,  5407,  2487,   996,   337,    88,    25,     6]),
 array([  0.        ,   3.41322212,   6.82644424,  10.23966637,
         13.65288849,  17.06611061,  20.47933273,  23.89255486,
         27.30577698,  30.7189991 ,  34.13222122]))

In [142]:
np.var(s3.run(z))

60.52026

In [143]:
np.var(s3.run(a))

20.724529